name: Federal Incentives
highlighter: pygments
baseurl: http://selectusa.github.io/federal-incentives
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
collections:
- events
